version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: ${PROJECT-sibdev}-db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  cache:
    image: redis
    container_name: ${PROJECT-sibdev}-cache
    restart: always
    ports:
      - ${REDIS_PORT-6379}:6379

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
      - cache
    restart: always
    container_name: ${PROJECT-sibdev}-server
    volumes:
      - ./static:/opt/pysetup/src/static
      - ./media:/opt/pysetup/src/media
    env_file: .env
    ports:
      - ${SERVER_PORT-8080}:8000

  open-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: rapidoc-run
    restart: always
    container_name: ${PROJECT-sibdev}-open-api
    env_file: .env
    depends_on:
      - server
    ports:
      - ${RAPIDOC_PORT-8090}:80

volumes:
  postgres_data: